from __future__ import annotations

import argparse
import json
import math
import os
import sys
from dataclasses import dataclass
from datetime import date, datetime, time, timezone
from hashlib import sha256
from pathlib import Path
from typing import Any

import pandas as pd
from sqlalchemy import bindparam, text

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

try:
    from app.core.settings import DatabaseSettings, get_settings
    from app.services.postgres_snapshot_repository import PostgresSnapshotRepository
except ModuleNotFoundError:
    from sqlalchemy import create_engine

    @dataclass(frozen=True)
    class DatabaseSettings:
        url: str = ""
        schema: str = "oil_research"
        echo: bool = False

    def get_settings() -> Any:
        raise RuntimeError(
            "app package is not available. Pass --database-url or use wrapper parameters "
            "-DatabaseHost/-DatabasePassword on the shared machine."
        )

    class PostgresSnapshotRepository:
        def __init__(self, settings: DatabaseSettings) -> None:
            self.settings = settings
            self.engine = create_engine(settings.url, echo=settings.echo) if settings.url else None

        def _fqtn(self, table_name: str) -> str:
            return f"{self.settings.schema}.{table_name}"

        def ensure_schema(self, schema_sql_path: str = "sql/v1_schema.sql") -> None:
            if not self.engine:
                return
            with self.engine.begin() as connection:
                connection.execute(text(f"create schema if not exists {self.settings.schema}"))
                connection.execute(text(f"""
                    create table if not exists {self._fqtn('dim_indicator')} (
                        indicator_id bigint generated by default as identity primary key,
                        indicator_code varchar(64) not null unique,
                        indicator_name varchar(128) not null,
                        category varchar(32) not null,
                        sub_category varchar(32),
                        unit varchar(32) not null,
                        freq varchar(16) not null,
                        value_type varchar(16) not null,
                        publish_lag_rule varchar(128),
                        fill_policy_default varchar(32) not null,
                        description text,
                        is_active boolean not null default true,
                        created_at timestamptz not null default now(),
                        updated_at timestamptz not null default now()
                    )
                """))
                connection.execute(text(f"""
                    create table if not exists {self._fqtn('dim_entity')} (
                        entity_id bigint generated by default as identity primary key,
                        entity_type varchar(32) not null,
                        entity_code varchar(64) not null unique,
                        entity_name varchar(128) not null,
                        parent_entity_id bigint references {self._fqtn('dim_entity')}(entity_id),
                        region_level varchar(16),
                        product_family varchar(32),
                        is_active boolean not null default true,
                        created_at timestamptz not null default now(),
                        updated_at timestamptz not null default now()
                    )
                """))
                connection.execute(text(f"""
                    create table if not exists {self._fqtn('dim_source')} (
                        source_id bigint generated by default as identity primary key,
                        source_code varchar(64) not null unique,
                        source_name varchar(128) not null,
                        source_type varchar(32) not null,
                        priority integer not null default 100,
                        sla_level varchar(16),
                        owner_team varchar(64),
                        is_active boolean not null default true,
                        created_at timestamptz not null default now(),
                        updated_at timestamptz not null default now()
                    )
                """))
                connection.execute(text(f"""
                    create table if not exists {self._fqtn('ods_raw_market')} (
                        raw_id bigint generated by default as identity primary key,
                        source_id bigint not null references {self._fqtn('dim_source')}(source_id),
                        source_record_id varchar(128) not null,
                        topic varchar(64) not null,
                        source_event_time timestamptz,
                        ingest_time timestamptz not null default now(),
                        payload jsonb not null,
                        payload_hash varchar(64) not null,
                        dt date not null,
                        unique (source_id, source_record_id, payload_hash)
                    )
                """))
                connection.execute(text(f"""
                    create table if not exists {self._fqtn('fact_market_timeseries')} (
                        ts_id bigint generated by default as identity primary key,
                        indicator_id bigint not null references {self._fqtn('dim_indicator')}(indicator_id),
                        entity_id bigint not null references {self._fqtn('dim_entity')}(entity_id),
                        observation_time timestamptz not null,
                        publish_time timestamptz not null,
                        freq varchar(16) not null,
                        value_num numeric(20, 6),
                        value_text text,
                        unit varchar(32) not null,
                        currency varchar(16),
                        source_id bigint not null references {self._fqtn('dim_source')}(source_id),
                        source_record_id varchar(128) not null,
                        is_final boolean not null default true,
                        revision_no integer not null default 1,
                        quality_flag varchar(16) not null default 'ok',
                        effective_from timestamptz not null,
                        effective_to timestamptz,
                        ingest_time timestamptz not null default now(),
                        dt date not null,
                        constraint chk_fact_market_timeseries_quality_flag
                            check (quality_flag in ('ok', 'missing', 'outlier', 'revised', 'fallback')),
                        unique (indicator_id, entity_id, observation_time, revision_no, source_id)
                    )
                """))
                connection.execute(text(f"create index if not exists idx_ods_raw_market_dt on {self._fqtn('ods_raw_market')} (dt)"))
                connection.execute(text(f"create index if not exists idx_fact_market_dt on {self._fqtn('fact_market_timeseries')} (dt)"))
                connection.execute(text(f"create index if not exists idx_fact_market_source_dt on {self._fqtn('fact_market_timeseries')} (source_id, dt desc)"))

        def _ensure_source_ids(self, connection: Any, source_codes: set[str]) -> dict[str, int]:
            normalized_codes = sorted(code for code in source_codes if code)
            if not normalized_codes:
                return {}
            seed_rows = []
            for code in normalized_codes:
                if code == "ganglian_excel_import":
                    meta = {"source_name": "Ganglian Excel import", "source_type": "manual_excel", "priority": 2}
                else:
                    meta = {"source_name": code, "source_type": "custom", "priority": 100}
                seed_rows.append({"source_code": code, **meta})
            connection.execute(text(f"""
                insert into {self._fqtn('dim_source')} (source_code, source_name, source_type, priority)
                values (:source_code, :source_name, :source_type, :priority)
                on conflict (source_code) do update set
                    source_name = excluded.source_name,
                    source_type = excluded.source_type,
                    priority = excluded.priority,
                    updated_at = now()
            """), seed_rows)
            rows = connection.execute(
                text(f"select source_id, source_code from {self._fqtn('dim_source')} where source_code in :source_codes")
                .bindparams(bindparam("source_codes", expanding=True)),
                {"source_codes": normalized_codes},
            ).mappings()
            return {str(row["source_code"]): int(row["source_id"]) for row in rows}

        def _ensure_indicators(self, connection: Any, rows: list[dict[str, Any]]) -> None:
            seed_rows = []
            seen: set[str] = set()
            for row in rows:
                indicator_code = str(row["indicator_code"])
                if indicator_code in seen:
                    continue
                seen.add(indicator_code)
                seed_rows.append({
                    "indicator_code": indicator_code,
                    "indicator_name": row["indicator_name"],
                    "category": row["category"],
                    "sub_category": row["sub_category"],
                    "unit": row["unit"],
                    "freq": row["freq"],
                    "value_type": row["value_type"],
                    "fill_policy_default": row["fill_policy_default"],
                    "description": row["description"],
                })
            if seed_rows:
                connection.execute(text(f"""
                    insert into {self._fqtn('dim_indicator')} (
                        indicator_code, indicator_name, category, sub_category, unit,
                        freq, value_type, fill_policy_default, description
                    )
                    values (
                        :indicator_code, :indicator_name, :category, :sub_category, :unit,
                        :freq, :value_type, :fill_policy_default, :description
                    )
                    on conflict (indicator_code) do update set
                        indicator_name = excluded.indicator_name,
                        category = excluded.category,
                        sub_category = excluded.sub_category,
                        unit = excluded.unit,
                        freq = excluded.freq,
                        value_type = excluded.value_type,
                        fill_policy_default = excluded.fill_policy_default,
                        description = excluded.description,
                        updated_at = now()
                """), seed_rows)

        def _ensure_entities(self, connection: Any, rows: list[dict[str, Any]]) -> None:
            seed_rows = []
            seen: set[str] = set()
            for row in rows:
                entity_code = str(row["entity_code"])
                if entity_code in seen:
                    continue
                seen.add(entity_code)
                seed_rows.append({
                    "entity_type": row["entity_type"],
                    "entity_code": entity_code,
                    "entity_name": row["entity_name"],
                    "region_level": row["region_level"],
                    "product_family": row["product_family"],
                })
            if seed_rows:
                connection.execute(text(f"""
                    insert into {self._fqtn('dim_entity')} (
                        entity_type, entity_code, entity_name, region_level, product_family
                    )
                    values (:entity_type, :entity_code, :entity_name, :region_level, :product_family)
                    on conflict (entity_code) do update set
                        entity_name = excluded.entity_name,
                        region_level = excluded.region_level,
                        product_family = excluded.product_family,
                        updated_at = now()
                """), seed_rows)


DEFAULT_SOURCE_CODE = "ganglian_excel_import"
DEFAULT_EXCEL_PATH = ROOT / "模型预测基础数据.xlsx"
SKIP_PRICE_SHEET_NAMES = {"汽油价格", "柴油价格"}
SKIP_PRICE_INDICATOR_CODES = {
    "sd_gas92_market",
    "cn_gas92_market",
    "east_china_gas92_market",
    "north_china_gas92_market",
    "south_china_gas92_market",
    "central_china_gas92_market",
    "northwest_gas92_market",
    "southwest_gas92_market",
    "northeast_gas92_market",
    "sd_diesel0_market",
    "cn_diesel0_market",
    "east_china_diesel0_market",
    "north_china_diesel0_market",
    "south_china_diesel0_market",
    "central_china_diesel0_market",
    "northwest_diesel0_market",
    "southwest_diesel0_market",
    "northeast_diesel0_market",
}

META_LABELS = {
    "indicator_name": "指标名称",
    "unit": "单位",
    "source_name": "数据来源",
    "source_indicator_code": "指标编码",
    "frequency": "频度",
    "date_range": "时间区间",
    "description": "指标描述",
    "end_time": "结束时间",
    "update_time": "更新时间",
}

CORE_INDICATOR_BY_NAME: dict[str, tuple[str, str, str, str, str, str]] = {
    "汽油：国六：92#：市场现汇价：山东（日）": (
        "sd_gas92_market",
        "山东92#汽油市场现汇价",
        "SHANDONG",
        "山东",
        "province",
        "GASOLINE_92",
    ),
    "汽油：国六：92#：市场价：中国（日）": (
        "cn_gas92_market",
        "全国92#汽油市场价",
        "NATIONAL",
        "全国",
        "country",
        "GASOLINE_92",
    ),
    "汽油：国六：92#：市场价：华东地区（日）": (
        "east_china_gas92_market",
        "华东92#汽油市场价",
        "EAST_CHINA",
        "华东",
        "macro_region",
        "GASOLINE_92",
    ),
    "汽油：国六：92#：市场价：华北地区（日）": (
        "north_china_gas92_market",
        "华北92#汽油市场价",
        "NORTH_CHINA",
        "华北",
        "macro_region",
        "GASOLINE_92",
    ),
    "汽油：国六：92#：市场价：华南地区（日）": (
        "south_china_gas92_market",
        "华南92#汽油市场价",
        "SOUTH_CHINA",
        "华南",
        "macro_region",
        "GASOLINE_92",
    ),
    "汽油：国六：92#：市场价：华中地区（日）": (
        "central_china_gas92_market",
        "华中92#汽油市场价",
        "CENTRAL_CHINA",
        "华中",
        "macro_region",
        "GASOLINE_92",
    ),
    "汽油：国六：92#：市场价：西北地区（日）": (
        "northwest_gas92_market",
        "西北92#汽油市场价",
        "NORTHWEST",
        "西北",
        "macro_region",
        "GASOLINE_92",
    ),
    "汽油：国六：92#：市场价：西南地区（日）": (
        "southwest_gas92_market",
        "西南92#汽油市场价",
        "SOUTHWEST",
        "西南",
        "macro_region",
        "GASOLINE_92",
    ),
    "汽油：国六：92#：市场价：东北地区（日）": (
        "northeast_gas92_market",
        "东北92#汽油市场价",
        "NORTHEAST",
        "东北",
        "macro_region",
        "GASOLINE_92",
    ),
    "柴油：国六：0#：市场现汇价：山东（日）": (
        "sd_diesel0_market",
        "山东0#柴油市场现汇价",
        "SHANDONG",
        "山东",
        "province",
        "DIESEL",
    ),
    "柴油：国六：0#：市场价：中国（日）": (
        "cn_diesel0_market",
        "全国0#柴油市场价",
        "NATIONAL",
        "全国",
        "country",
        "DIESEL",
    ),
    "柴油：国六：0#：市场价：华东地区（日）": (
        "east_china_diesel0_market",
        "华东0#柴油市场价",
        "EAST_CHINA",
        "华东",
        "macro_region",
        "DIESEL",
    ),
    "柴油：国六：0#：市场价：华北地区（日）": (
        "north_china_diesel0_market",
        "华北0#柴油市场价",
        "NORTH_CHINA",
        "华北",
        "macro_region",
        "DIESEL",
    ),
    "柴油：国六：0#：市场价：华南地区（日）": (
        "south_china_diesel0_market",
        "华南0#柴油市场价",
        "SOUTH_CHINA",
        "华南",
        "macro_region",
        "DIESEL",
    ),
    "柴油：国六：0#：市场价：华中地区（日）": (
        "central_china_diesel0_market",
        "华中0#柴油市场价",
        "CENTRAL_CHINA",
        "华中",
        "macro_region",
        "DIESEL",
    ),
    "柴油：国六：0#：市场价：西北地区（日）": (
        "northwest_diesel0_market",
        "西北0#柴油市场价",
        "NORTHWEST",
        "西北",
        "macro_region",
        "DIESEL",
    ),
    "柴油：国六：0#：市场价：西南地区（日）": (
        "southwest_diesel0_market",
        "西南0#柴油市场价",
        "SOUTHWEST",
        "西南",
        "macro_region",
        "DIESEL",
    ),
    "柴油：国六：0#：市场价：东北地区（日）": (
        "northeast_diesel0_market",
        "东北0#柴油市场价",
        "NORTHEAST",
        "东北",
        "macro_region",
        "DIESEL",
    ),
}

CDU_UTILIZATION_INDICATOR_BY_NAME: dict[str, tuple[str, str, str, str, str, str]] = {
    '成品油：常减压：产能利用率：山东：独立炼厂（周）': ('shandong_cdu_utilization_weekly', '山东独立炼厂成品油常减压产能利用率', 'SHANDONG_REFINERY', '山东独立炼厂', 'province', "REFINED_OIL"),
    '成品油：常减压：产能利用率：华东地区（除山东）：独立炼厂（周）': ('east_china_cdu_utilization_weekly', '华东独立炼厂成品油常减压产能利用率', 'EAST_CHINA_REFINERY', '华东独立炼厂', 'macro_region', "REFINED_OIL"),
    '成品油：常减压：产能利用率：华北地区：独立炼厂（周）': ('north_china_cdu_utilization_weekly', '华北独立炼厂成品油常减压产能利用率', 'NORTH_CHINA_REFINERY', '华北独立炼厂', 'macro_region', "REFINED_OIL"),
    '成品油：常减压：产能利用率：华南地区：独立炼厂（周）': ('south_china_cdu_utilization_weekly', '华南独立炼厂成品油常减压产能利用率', 'SOUTH_CHINA_REFINERY', '华南独立炼厂', 'macro_region', "REFINED_OIL"),
    '成品油：常减压：产能利用率：华中地区：独立炼厂（周）': ('central_china_cdu_utilization_weekly', '华中独立炼厂成品油常减压产能利用率', 'CENTRAL_CHINA_REFINERY', '华中独立炼厂', 'macro_region', "REFINED_OIL"),
    '成品油：常减压：产能利用率：西北地区：独立炼厂（周）': ('northwest_cdu_utilization_weekly', '西北独立炼厂成品油常减压产能利用率', 'NORTHWEST_REFINERY', '西北独立炼厂', 'macro_region', "REFINED_OIL"),
    '成品油：常减压：产能利用率：西南地区：独立炼厂（周）': ('southwest_cdu_utilization_weekly', '西南独立炼厂成品油常减压产能利用率', 'SOUTHWEST_REFINERY', '西南独立炼厂', 'macro_region', "REFINED_OIL"),
    '成品油：常减压：产能利用率：东北地区：独立炼厂（周）': ('northeast_cdu_utilization_weekly', '东北独立炼厂成品油常减压产能利用率', 'NORTHEAST_REFINERY', '东北独立炼厂', 'macro_region', "REFINED_OIL"),
}
CORE_INDICATOR_BY_NAME.update(CDU_UTILIZATION_INDICATOR_BY_NAME)

REGIONAL_SHIPMENTS_INDICATOR_BY_NAME: dict[str, tuple[str, str, str, str, str, str]] = {
    '汽油：出货量：华东地区（除山东）：独立炼厂（周）': ('east_china_gasoline_shipments_weekly', '华东独立炼厂汽油出货量', 'EAST_CHINA_REFINERY_GASOLINE', '华东独立炼厂汽油', 'macro_region', 'GASOLINE_92'),
    '汽油：出货量：华北地区：独立炼厂（周）': ('north_china_gasoline_shipments_weekly', '华北独立炼厂汽油出货量', 'NORTH_CHINA_REFINERY_GASOLINE', '华北独立炼厂汽油', 'macro_region', 'GASOLINE_92'),
    '汽油：出货量：华南地区：独立炼厂（周）': ('south_china_gasoline_shipments_weekly', '华南独立炼厂汽油出货量', 'SOUTH_CHINA_REFINERY_GASOLINE', '华南独立炼厂汽油', 'macro_region', 'GASOLINE_92'),
    '汽油：出货量：华中地区：独立炼厂（周）': ('central_china_gasoline_shipments_weekly', '华中独立炼厂汽油出货量', 'CENTRAL_CHINA_REFINERY_GASOLINE', '华中独立炼厂汽油', 'macro_region', 'GASOLINE_92'),
    '汽油：出货量：西北地区：独立炼厂（周）': ('northwest_gasoline_shipments_weekly', '西北独立炼厂汽油出货量', 'NORTHWEST_REFINERY_GASOLINE', '西北独立炼厂汽油', 'macro_region', 'GASOLINE_92'),
    '汽油：出货量：西南地区：独立炼厂（周）': ('southwest_gasoline_shipments_weekly', '西南独立炼厂汽油出货量', 'SOUTHWEST_REFINERY_GASOLINE', '西南独立炼厂汽油', 'macro_region', 'GASOLINE_92'),
    '汽油：出货量：东北地区：独立炼厂（周）': ('northeast_gasoline_shipments_weekly', '东北独立炼厂汽油出货量', 'NORTHEAST_REFINERY_GASOLINE', '东北独立炼厂汽油', 'macro_region', 'GASOLINE_92'),
    '柴油：出货量：华东地区（除山东）：独立炼厂（周）': ('east_china_diesel_shipments_weekly', '华东独立炼厂柴油出货量', 'EAST_CHINA_REFINERY_DIESEL', '华东独立炼厂柴油', 'macro_region', 'DIESEL'),
    '柴油：出货量：华北地区：独立炼厂（周）': ('north_china_diesel_shipments_weekly', '华北独立炼厂柴油出货量', 'NORTH_CHINA_REFINERY_DIESEL', '华北独立炼厂柴油', 'macro_region', 'DIESEL'),
    '柴油：出货量：华南地区：独立炼厂（周）': ('south_china_diesel_shipments_weekly', '华南独立炼厂柴油出货量', 'SOUTH_CHINA_REFINERY_DIESEL', '华南独立炼厂柴油', 'macro_region', 'DIESEL'),
    '柴油：出货量：华中地区：独立炼厂（周）': ('central_china_diesel_shipments_weekly', '华中独立炼厂柴油出货量', 'CENTRAL_CHINA_REFINERY_DIESEL', '华中独立炼厂柴油', 'macro_region', 'DIESEL'),
    '柴油：出货量：西北地区：独立炼厂（周）': ('northwest_diesel_shipments_weekly', '西北独立炼厂柴油出货量', 'NORTHWEST_REFINERY_DIESEL', '西北独立炼厂柴油', 'macro_region', 'DIESEL'),
    '柴油：出货量：西南地区：独立炼厂（周）': ('southwest_diesel_shipments_weekly', '西南独立炼厂柴油出货量', 'SOUTHWEST_REFINERY_DIESEL', '西南独立炼厂柴油', 'macro_region', 'DIESEL'),
    '柴油：出货量：东北地区：独立炼厂（周）': ('northeast_diesel_shipments_weekly', '东北独立炼厂柴油出货量', 'NORTHEAST_REFINERY_DIESEL', '东北独立炼厂柴油', 'macro_region', 'DIESEL'),
}
CORE_INDICATOR_BY_NAME.update(REGIONAL_SHIPMENTS_INDICATOR_BY_NAME)

CORE_INDICATOR_BY_SOURCE_CODE: dict[str, tuple[str, str, str, str, str, str]] = {
    "ID01242419": ("cn_gas92_market", "全国92#汽油市场价", "NATIONAL", "全国", "country", "GASOLINE_92"),
    "ID01153195": ("sd_gas92_market", "山东92#汽油市场现汇价", "SHANDONG", "山东", "province", "GASOLINE_92"),
    "ID00402382": ("east_china_gas92_market", "华东92#汽油市场价", "EAST_CHINA", "华东", "macro_region", "GASOLINE_92"),
    "ID00397794": ("central_china_gas92_market", "华中92#汽油市场价", "CENTRAL_CHINA", "华中", "macro_region", "GASOLINE_92"),
    "ID00397789": ("north_china_gas92_market", "华北92#汽油市场价", "NORTH_CHINA", "华北", "macro_region", "GASOLINE_92"),
    "ID00397791": ("south_china_gas92_market", "华南92#汽油市场价", "SOUTH_CHINA", "华南", "macro_region", "GASOLINE_92"),
    "ID00397792": ("northwest_gas92_market", "西北92#汽油市场价", "NORTHWEST", "西北", "macro_region", "GASOLINE_92"),
    "ID00397793": ("southwest_gas92_market", "西南92#汽油市场价", "SOUTHWEST", "西南", "macro_region", "GASOLINE_92"),
    "ID00397790": ("northeast_gas92_market", "东北92#汽油市场价", "NORTHEAST", "东北", "macro_region", "GASOLINE_92"),
    "ID01242417": ("cn_diesel0_market", "全国0#柴油市场价", "NATIONAL", "全国", "country", "DIESEL"),
    "ID01152761": ("sd_diesel0_market", "山东0#柴油市场现汇价", "SHANDONG", "山东", "province", "DIESEL"),
    "ID00397529": ("east_china_diesel0_market", "华东0#柴油市场价", "EAST_CHINA", "华东", "macro_region", "DIESEL"),
    "ID00397533": ("central_china_diesel0_market", "华中0#柴油市场价", "CENTRAL_CHINA", "华中", "macro_region", "DIESEL"),
    "ID00397528": ("north_china_diesel0_market", "华北0#柴油市场价", "NORTH_CHINA", "华北", "macro_region", "DIESEL"),
    "ID00397530": ("south_china_diesel0_market", "华南0#柴油市场价", "SOUTH_CHINA", "华南", "macro_region", "DIESEL"),
    "ID00397531": ("northwest_diesel0_market", "西北0#柴油市场价", "NORTHWEST", "西北", "macro_region", "DIESEL"),
    "ID00397532": ("southwest_diesel0_market", "西南0#柴油市场价", "SOUTHWEST", "西南", "macro_region", "DIESEL"),
    "ID00397527": ("northeast_diesel0_market", "东北0#柴油市场价", "NORTHEAST", "东北", "macro_region", "DIESEL"),
    "ID01374956": ("sd_crude_run_weekly", "山东独立炼厂常减压产能利用率", "SHANDONG_REFINERY", "山东独立炼厂", "province", "REFINED_OIL"),
    "ID01381881": ("sd_gas_production_weekly", "山东独立炼厂汽油产量", "SHANDONG_REFINERY_GASOLINE", "山东独立炼厂汽油", "province", "GASOLINE_92"),
    "ID01374903": ("sd_gas_sales_weekly", "山东独立炼厂汽油出货量", "SHANDONG_REFINERY_GASOLINE", "山东独立炼厂汽油", "province", "GASOLINE_92"),
    "ID01374817": ("shandong_independent_refinery_inventory", "山东独立炼厂汽油厂内库存", "SHANDONG_REFINERY_GASOLINE", "山东独立炼厂汽油", "province", "GASOLINE_92"),
    "ID01374828": ("shandong_diesel_inventory", "山东独立炼厂柴油厂内库存", "SHANDONG_REFINERY_DIESEL", "山东独立炼厂柴油", "province", "DIESEL"),
}



CORE_INDICATOR_BY_SOURCE_CODE.update({
    'ID01242419': ('cn_gas92_market', '全国92#汽油市场价', 'NATIONAL', '全国', 'country', 'GASOLINE_92'),
    'ID01153195': ('sd_gas92_market', '山东92#汽油市场现汇价', 'SHANDONG', '山东', 'province', 'GASOLINE_92'),
    'ID00402382': ('east_china_gas92_market', '华东92#汽油市场价', 'EAST_CHINA', '华东', 'macro_region', 'GASOLINE_92'),
    'ID00397794': ('central_china_gas92_market', '华中92#汽油市场价', 'CENTRAL_CHINA', '华中', 'macro_region', 'GASOLINE_92'),
    'ID00397789': ('north_china_gas92_market', '华北92#汽油市场价', 'NORTH_CHINA', '华北', 'macro_region', 'GASOLINE_92'),
    'ID00397791': ('south_china_gas92_market', '华南92#汽油市场价', 'SOUTH_CHINA', '华南', 'macro_region', 'GASOLINE_92'),
    'ID00397792': ('northwest_gas92_market', '西北92#汽油市场价', 'NORTHWEST', '西北', 'macro_region', 'GASOLINE_92'),
    'ID00397793': ('southwest_gas92_market', '西南92#汽油市场价', 'SOUTHWEST', '西南', 'macro_region', 'GASOLINE_92'),
    'ID00397790': ('northeast_gas92_market', '东北92#汽油市场价', 'NORTHEAST', '东北', 'macro_region', 'GASOLINE_92'),
    'ID01242417': ('cn_diesel0_market', '全国0#柴油市场价', 'NATIONAL', '全国', 'country', 'DIESEL'),
    'ID01152761': ('sd_diesel0_market', '山东0#柴油市场现汇价', 'SHANDONG', '山东', 'province', 'DIESEL'),
    'ID00397529': ('east_china_diesel0_market', '华东0#柴油市场价', 'EAST_CHINA', '华东', 'macro_region', 'DIESEL'),
    'ID00397533': ('central_china_diesel0_market', '华中0#柴油市场价', 'CENTRAL_CHINA', '华中', 'macro_region', 'DIESEL'),
    'ID00397528': ('north_china_diesel0_market', '华北0#柴油市场价', 'NORTH_CHINA', '华北', 'macro_region', 'DIESEL'),
    'ID00397530': ('south_china_diesel0_market', '华南0#柴油市场价', 'SOUTH_CHINA', '华南', 'macro_region', 'DIESEL'),
    'ID00397531': ('northwest_diesel0_market', '西北0#柴油市场价', 'NORTHWEST', '西北', 'macro_region', 'DIESEL'),
    'ID00397532': ('southwest_diesel0_market', '西南0#柴油市场价', 'SOUTHWEST', '西南', 'macro_region', 'DIESEL'),
    'ID00397527': ('northeast_diesel0_market', '东北0#柴油市场价', 'NORTHEAST', '东北', 'macro_region', 'DIESEL'),
    'ID01374956': ('sd_crude_run_weekly', '山东独立炼厂常减压产能利用率', 'SHANDONG_REFINERY', '山东独立炼厂', 'province', 'REFINED_OIL'),
    'ID01381881': ('sd_gas_production_weekly', '山东独立炼厂汽油产量', 'SHANDONG_REFINERY_GASOLINE', '山东独立炼厂汽油', 'province', 'GASOLINE_92'),
    'ID01374903': ('sd_gas_sales_weekly', '山东独立炼厂汽油出货量', 'SHANDONG_REFINERY_GASOLINE', '山东独立炼厂汽油', 'province', 'GASOLINE_92'),
    'ID01374817': ('shandong_independent_refinery_inventory', '山东独立炼厂汽油厂内库存', 'SHANDONG_REFINERY_GASOLINE', '山东独立炼厂汽油', 'province', 'GASOLINE_92'),
    'ID01374828': ('shandong_diesel_inventory', '山东独立炼厂柴油厂内库存', 'SHANDONG_REFINERY_DIESEL', '山东独立炼厂柴油', 'province', 'DIESEL'),
})

MAPPED_INDICATOR_CODES = {
    *(value[0] for value in CORE_INDICATOR_BY_NAME.values()),
    *(value[0] for value in CORE_INDICATOR_BY_SOURCE_CODE.values()),
}


@dataclass(frozen=True)
class SeriesColumn:
    sheet_name: str
    column_index: int
    raw_indicator_name: str
    indicator_code: str
    indicator_name: str
    unit: str
    source_name: str
    source_indicator_code: str
    frequency: str
    date_range: str
    description: str
    end_time: str
    update_time: str
    entity_code: str
    entity_name: str
    region_level: str
    product_family: str
    is_core_mapped: bool


def clean_text(value: Any) -> str:
    if value is None:
        return ""
    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass
    return str(value).strip()


def parse_date(value: Any) -> date | None:
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    raw = clean_text(value)
    if not raw:
        return None
    raw = raw.replace("/", "-").replace("～", "-")
    try:
        parsed = pd.Timestamp(raw[:10])
    except Exception:
        return None
    if pd.isna(parsed):
        return None
    return parsed.date()


def parse_number(value: Any) -> float | None:
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except Exception:
        pass
    if isinstance(value, str):
        raw = value.strip().replace(",", "")
        if not raw or raw in {"-", "--", "—", "NaN", "nan", "None"}:
            return None
        if raw.endswith("%"):
            raw = raw[:-1]
        try:
            numeric = float(raw)
        except ValueError:
            return None
    else:
        try:
            numeric = float(value)
        except Exception:
            return None
    return numeric if math.isfinite(numeric) else None


def payload_hash(payload: dict[str, Any]) -> str:
    body = json.dumps(payload, ensure_ascii=False, sort_keys=True, default=str).encode("utf-8")
    return sha256(body).hexdigest()


def source_record_id(source_code: str, payload: dict[str, Any]) -> str:
    digest = payload_hash(payload)[:24]
    return f"{source_code}:{digest}"


def find_meta_rows(raw: pd.DataFrame) -> dict[str, int]:
    rows: dict[str, int] = {}
    if raw.empty:
        return rows
    for row_idx in range(raw.shape[0]):
        row_values = {clean_text(raw.iat[row_idx, col_idx]) for col_idx in range(raw.shape[1])}
        for key, label in META_LABELS.items():
            if key not in rows and label in row_values:
                rows[key] = row_idx
        if len(rows) == len(META_LABELS):
            break
    return rows


def normalize_frequency(value: str, indicator_name: str) -> str:
    text = f"{value} {indicator_name}"
    if "日" in text:
        return "daily"
    if "周" in text:
        return "weekly"
    if "月" in text:
        return "monthly"
    if "季" in text:
        return "quarterly"
    if "年" in text:
        return "yearly"
    return "unknown"


def fallback_indicator_code(source_indicator_code: str, indicator_name: str) -> str:
    if source_indicator_code:
        safe_code = "".join(ch.lower() if ch.isalnum() else "_" for ch in source_indicator_code)
        safe_code = "_".join(part for part in safe_code.split("_") if part)
        if safe_code:
            return f"ganglian_{safe_code}"[:64]
    digest = sha256(indicator_name.encode("utf-8")).hexdigest()[:16]
    return f"ganglian_{digest}"


def infer_entity(indicator_name: str) -> tuple[str, str, str]:
    region_map = [
        ("山东", "SHANDONG", "山东", "province"),
        ("中国", "NATIONAL", "全国", "country"),
        ("华东地区", "EAST_CHINA", "华东", "macro_region"),
        ("华北地区", "NORTH_CHINA", "华北", "macro_region"),
        ("华南地区", "SOUTH_CHINA", "华南", "macro_region"),
        ("华中地区", "CENTRAL_CHINA", "华中", "macro_region"),
        ("西北地区", "NORTHWEST", "西北", "macro_region"),
        ("西南地区", "SOUTHWEST", "西南", "macro_region"),
        ("东北地区", "NORTHEAST", "东北", "macro_region"),
    ]
    for token, code, name, level in region_map:
        if token in indicator_name:
            return code, name, level
    return "NATIONAL", "全国", "country"


def infer_product_family(indicator_name: str) -> str:
    if "柴油" in indicator_name:
        return "DIESEL"
    if "汽油" in indicator_name:
        return "GASOLINE_92" if "92#" in indicator_name else "GASOLINE"
    if "原油" in indicator_name:
        return "CRUDE"
    return "REFINED_OIL"


def build_series_columns(raw: pd.DataFrame, sheet_name: str) -> tuple[list[SeriesColumn], int]:
    meta_rows = find_meta_rows(raw)
    indicator_row = meta_rows.get("indicator_name")
    if indicator_row is None and raw.shape[0] >= 10:
        first_label = clean_text(raw.iat[0, 0]) if raw.shape[1] else ""
        row2_has_values = any(clean_text(raw.iat[1, col_idx]) for col_idx in range(1, raw.shape[1]))
        row11_has_date = parse_date(raw.iat[10, 0]) is not None
        if first_label == "钢联数据" and row2_has_values and row11_has_date:
            meta_rows = {
                "indicator_name": 1,
                "unit": 2,
                "source_name": 3,
                "source_indicator_code": 4,
                "frequency": 5,
                "date_range": 6,
                "description": 7,
                "end_time": 8,
                "update_time": 9,
            }
            indicator_row = 1
    if indicator_row is None:
        return [], 0
    data_start = max(meta_rows.values()) + 1
    columns: list[SeriesColumn] = []
    for col_idx in range(1, raw.shape[1]):
        raw_indicator_name = clean_text(raw.iat[indicator_row, col_idx])
        if not raw_indicator_name:
            continue
        unit = clean_text(raw.iat[meta_rows["unit"], col_idx]) if "unit" in meta_rows else ""
        source_name = clean_text(raw.iat[meta_rows["source_name"], col_idx]) if "source_name" in meta_rows else ""
        source_indicator_code = (
            clean_text(raw.iat[meta_rows["source_indicator_code"], col_idx])
            if "source_indicator_code" in meta_rows
            else ""
        )
        frequency_hint = clean_text(raw.iat[meta_rows["frequency"], col_idx]) if "frequency" in meta_rows else ""
        date_range = clean_text(raw.iat[meta_rows["date_range"], col_idx]) if "date_range" in meta_rows else ""
        description = clean_text(raw.iat[meta_rows["description"], col_idx]) if "description" in meta_rows else ""
        end_time = clean_text(raw.iat[meta_rows["end_time"], col_idx]) if "end_time" in meta_rows else ""
        update_time = clean_text(raw.iat[meta_rows["update_time"], col_idx]) if "update_time" in meta_rows else ""
        mapped = CORE_INDICATOR_BY_NAME.get(raw_indicator_name) or CORE_INDICATOR_BY_SOURCE_CODE.get(source_indicator_code)
        if mapped:
            indicator_code, indicator_name, entity_code, entity_name, region_level, product_family = mapped
            is_core_mapped = True
        else:
            indicator_code = fallback_indicator_code(source_indicator_code, raw_indicator_name)
            indicator_name = raw_indicator_name
            entity_code, entity_name, region_level = infer_entity(raw_indicator_name)
            product_family = infer_product_family(raw_indicator_name)
            is_core_mapped = False
        columns.append(
            SeriesColumn(
                sheet_name=sheet_name,
                column_index=col_idx,
                raw_indicator_name=raw_indicator_name,
                indicator_code=indicator_code,
                indicator_name=indicator_name,
                unit=unit,
                source_name=source_name,
                source_indicator_code=source_indicator_code,
                frequency=normalize_frequency(frequency_hint, raw_indicator_name),
                date_range=date_range,
                description=description,
                end_time=end_time,
                update_time=update_time,
                entity_code=entity_code,
                entity_name=entity_name,
                region_level=region_level,
                product_family=product_family,
                is_core_mapped=is_core_mapped,
            )
        )
    return columns, data_start


def extract_excel_timeseries(
    path: Path,
    *,
    source_code: str,
    start_date: date | None = None,
    end_date: date | None = None,
    mapped_only: bool = True,
    skip_sheet_names: set[str] | tuple[str, ...] = (),
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Excel file not found: {path}")
    excel = pd.ExcelFile(path)
    indicator_rows: dict[str, dict[str, Any]] = {}
    data_rows: list[dict[str, Any]] = []
    sheet_summaries: list[dict[str, Any]] = []
    skipped_sheets: list[str] = []

    skip_sheet_name_set = set(skip_sheet_names or ())

    for sheet_name in excel.sheet_names:
        if sheet_name in skip_sheet_name_set:
            skipped_sheets.append(sheet_name)
            continue
        raw = pd.read_excel(path, sheet_name=sheet_name, header=None)
        if raw.empty:
            skipped_sheets.append(sheet_name)
            continue
        series_columns, data_start = build_series_columns(raw, sheet_name)
        if not series_columns:
            skipped_sheets.append(sheet_name)
            continue
        if mapped_only:
            series_columns = [series for series in series_columns if series.is_core_mapped]
        if skip_sheet_name_set:
            series_columns = [series for series in series_columns if series.indicator_code not in SKIP_PRICE_INDICATOR_CODES]
        if not series_columns:
            skipped_sheets.append(sheet_name)
            continue
        rows_before = len(data_rows)
        for series in series_columns:
            indicator_rows.setdefault(
                series.indicator_code,
                {
                    "indicator_code": series.indicator_code,
                    "indicator_name": series.indicator_name,
                    "category": "refined_oil",
                    "sub_category": "ganglian_excel",
                    "unit": series.unit,
                    "freq": series.frequency,
                    "value_type": "number",
                    "fill_policy_default": "latest_available",
                    "description": (
                        f"钢联Excel导入；原指标名称={series.raw_indicator_name}；"
                        f"原指标编码={series.source_indicator_code}；指标描述={series.description}"
                    ),
                    "entity_type": "market_region",
                    "entity_code": series.entity_code,
                    "entity_name": series.entity_name,
                    "region_level": series.region_level,
                    "product_family": series.product_family,
                },
            )
        for row_idx in range(data_start, raw.shape[0]):
            observation_date = parse_date(raw.iat[row_idx, 0])
            if observation_date is None:
                continue
            if start_date and observation_date < start_date:
                continue
            if end_date and observation_date > end_date:
                continue
            for series in series_columns:
                value_num = parse_number(raw.iat[row_idx, series.column_index])
                if value_num is None:
                    continue
                record_payload = {
                    "file_name": path.name,
                    "sheet_name": sheet_name,
                    "row_number": row_idx + 1,
                    "column_number": series.column_index + 1,
                    "observation_date": observation_date.isoformat(),
                    "indicator_code": series.indicator_code,
                    "raw_indicator_name": series.raw_indicator_name,
                    "source_indicator_code": series.source_indicator_code,
                    "value_num": value_num,
                    "unit": series.unit,
                }
                data_rows.append(
                    {
                        "indicator_code": series.indicator_code,
                        "entity_code": series.entity_code,
                        "observation_date": observation_date,
                        "value_num": value_num,
                        "unit": series.unit,
                        "freq": series.frequency,
                        "source_record_id": source_record_id(source_code, record_payload),
                        "raw_payload": record_payload,
                    }
                )
        sheet_summaries.append(
            {
                "sheet_name": sheet_name,
                "indicator_count": len(series_columns),
                "core_mapped_indicator_count": sum(1 for item in series_columns if item.is_core_mapped),
                "data_start_row": data_start + 1,
                "timeseries_rows": len(data_rows) - rows_before,
            }
        )

    summary = {
        "source_code": source_code,
        "excel_path": str(path),
        "sheet_count": len(excel.sheet_names),
        "skipped_sheets": skipped_sheets,
        "indicator_count": len(indicator_rows),
        "core_mapped_indicator_count": sum(1 for item in indicator_rows.values() if item["indicator_code"] in MAPPED_INDICATOR_CODES),
        "timeseries_row_count": len(data_rows),
        "date_min": min((row["observation_date"] for row in data_rows), default=None),
        "date_max": max((row["observation_date"] for row in data_rows), default=None),
        "sheets": sheet_summaries,
        "mapped_only": mapped_only,
    }
    return list(indicator_rows.values()), data_rows, summary


def purge_source_timeseries(repository: PostgresSnapshotRepository, source_code: str) -> dict[str, int]:
    if not repository.engine:
        return {"fact_market_timeseries": 0, "ods_raw_market": 0}
    with repository.engine.begin() as connection:
        source_id = connection.execute(
            text(f"select source_id from {repository._fqtn('dim_source')} where source_code = :source_code"),
            {"source_code": source_code},
        ).scalar_one_or_none()
        if source_id is None:
            return {"fact_market_timeseries": 0, "ods_raw_market": 0}
        fact_result = connection.execute(
            text(f"delete from {repository._fqtn('fact_market_timeseries')} where source_id = :source_id"),
            {"source_id": source_id},
        )
        raw_result = connection.execute(
            text(f"delete from {repository._fqtn('ods_raw_market')} where source_id = :source_id"),
            {"source_id": source_id},
        )
    return {
        "fact_market_timeseries": int(fact_result.rowcount or 0),
        "ods_raw_market": int(raw_result.rowcount or 0),
    }


def upsert_timeseries(
    repository: PostgresSnapshotRepository,
    *,
    source_code: str,
    indicator_rows: list[dict[str, Any]],
    data_rows: list[dict[str, Any]],
    summary: dict[str, Any],
) -> int:
    if not repository.engine or not data_rows:
        return 0
    now = datetime.now(timezone.utc)
    with repository.engine.begin() as connection:
        source_id = repository._ensure_source_ids(connection, {source_code})[source_code]
        repository._ensure_indicators(connection, indicator_rows)
        repository._ensure_entities(connection, indicator_rows)
        raw_payload = {
            "summary": summary,
            "indicator_codes": sorted({row["indicator_code"] for row in indicator_rows}),
        }
        connection.execute(
            text(
                f"""
                insert into {repository._fqtn('ods_raw_market')} (
                    source_id, source_record_id, topic, source_event_time, payload, payload_hash, dt
                )
                values (
                    :source_id, :source_record_id, :topic, :source_event_time,
                    cast(:payload as jsonb), :payload_hash, :dt
                )
                on conflict (source_id, source_record_id, payload_hash) do nothing
                """
            ),
            {
                "source_id": source_id,
                "source_record_id": source_record_id(source_code, raw_payload),
                "topic": "ganglian_excel_timeseries_import",
                "source_event_time": now,
                "payload": json.dumps(raw_payload, ensure_ascii=False, default=str),
                "payload_hash": payload_hash(raw_payload),
                "dt": date.today(),
            },
        )
        rows = list(
            connection.execute(
                text(
                    f"""
                    select i.indicator_id, i.indicator_code, e.entity_id, e.entity_code
                    from {repository._fqtn('dim_indicator')} i
                    join {repository._fqtn('dim_entity')} e on 1 = 1
                    where i.indicator_code in :indicator_codes
                      and e.entity_code in :entity_codes
                    """
                ).bindparams(bindparam("indicator_codes", expanding=True), bindparam("entity_codes", expanding=True)),
                {
                    "indicator_codes": [row["indicator_code"] for row in indicator_rows],
                    "entity_codes": [row["entity_code"] for row in indicator_rows],
                },
            ).mappings()
        )
        indicator_id_map = {str(row["indicator_code"]): int(row["indicator_id"]) for row in rows}
        entity_id_map = {str(row["entity_code"]): int(row["entity_id"]) for row in rows}
        ts_rows: list[dict[str, Any]] = []
        for row in data_rows:
            indicator_id = indicator_id_map.get(row["indicator_code"])
            entity_id = entity_id_map.get(row["entity_code"])
            if not indicator_id or not entity_id:
                continue
            unit = row["unit"] or ""
            observation_time = datetime.combine(row["observation_date"], time(0, 0))
            ts_rows.append(
                {
                    "indicator_id": indicator_id,
                    "entity_id": entity_id,
                    "observation_time": observation_time,
                    "publish_time": now,
                    "freq": row["freq"],
                    "value_num": row["value_num"],
                    "value_text": None,
                    "unit": unit,
                    "currency": "CNY" if "元" in unit else None,
                    "source_id": source_id,
                    "source_record_id": row["source_record_id"],
                    "is_final": True,
                    "revision_no": 1,
                    "quality_flag": "ok",
                    "effective_from": now,
                    "effective_to": None,
                    "dt": row["observation_date"],
                }
            )
        statement = text(
            f"""
            insert into {repository._fqtn('fact_market_timeseries')} (
                indicator_id, entity_id, observation_time, publish_time, freq, value_num,
                value_text, unit, currency, source_id, source_record_id, is_final,
                revision_no, quality_flag, effective_from, effective_to, dt
            )
            values (
                :indicator_id, :entity_id, :observation_time, :publish_time, :freq, :value_num,
                :value_text, :unit, :currency, :source_id, :source_record_id, :is_final,
                :revision_no, :quality_flag, :effective_from, :effective_to, :dt
            )
            on conflict (indicator_id, entity_id, observation_time, revision_no, source_id)
            do update set
                publish_time = excluded.publish_time,
                value_num = excluded.value_num,
                source_record_id = excluded.source_record_id,
                quality_flag = excluded.quality_flag,
                effective_from = excluded.effective_from,
                dt = excluded.dt
            """
        )
        saved = 0
        chunk_size = 5000
        for start in range(0, len(ts_rows), chunk_size):
            result = connection.execute(statement, ts_rows[start : start + chunk_size])
            saved += int(result.rowcount or 0)
        return saved


def resolve_database_settings(args: argparse.Namespace) -> DatabaseSettings:
    database_url = args.database_url or os.getenv("OIL_RESEARCH_DB_URL")
    schema = args.schema or os.getenv("OIL_RESEARCH_DB_SCHEMA")
    if database_url:
        return DatabaseSettings(url=database_url, schema=schema or "oil_research", echo=False)
    settings = get_settings()
    if schema and schema != settings.database.schema:
        return DatabaseSettings(url=settings.database.url, schema=schema, echo=settings.database.echo)
    return settings.database


def write_summary(path: Path, summary: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(summary, ensure_ascii=False, indent=2, default=str), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Import Ganglian horizontal Excel indicators into PostgreSQL.")
    parser.add_argument("--excel", default=str(os.getenv("GANGLIAN_EXCEL_PATH") or DEFAULT_EXCEL_PATH))
    parser.add_argument("--source-code", default=DEFAULT_SOURCE_CODE)
    parser.add_argument("--database-url", default="")
    parser.add_argument("--schema", default="")
    parser.add_argument("--start-date", default="")
    parser.add_argument("--end-date", default="")
    parser.add_argument("--all-columns", action="store_true")
    parser.add_argument("--include-price-sheets", action="store_true", help="Import gasoline/diesel price sheets as well.")
    parser.add_argument("--replace-source", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--summary-output", default="artifacts/ganglian_excel_import_summary.json")
    args = parser.parse_args()

    excel_path = Path(args.excel).expanduser().resolve()
    start_date = parse_date(args.start_date) if args.start_date else None
    end_date = parse_date(args.end_date) if args.end_date else None
    indicator_rows, data_rows, summary = extract_excel_timeseries(
        excel_path,
        source_code=args.source_code,
        start_date=start_date,
        end_date=end_date,
        mapped_only=not args.all_columns,
        skip_sheet_names=() if args.include_price_sheets else SKIP_PRICE_SHEET_NAMES,
    )
    summary["dry_run"] = bool(args.dry_run)
    summary["start_date_filter"] = start_date
    summary["end_date_filter"] = end_date
    summary["mapped_indicator_codes"] = sorted(
        row["indicator_code"]
        for row in indicator_rows
        if row["indicator_code"] in MAPPED_INDICATOR_CODES
    )
    summary["unmapped_indicators"] = [
        {
            "indicator_code": row["indicator_code"],
            "indicator_name": row["indicator_name"],
            "unit": row["unit"],
        }
        for row in indicator_rows
        if row["indicator_code"] not in MAPPED_INDICATOR_CODES
    ]

    if not args.dry_run:
        database_settings = resolve_database_settings(args)
        repository = PostgresSnapshotRepository(database_settings)
        repository.ensure_schema()
        if args.replace_source:
            summary["purged_rows"] = purge_source_timeseries(repository, args.source_code)
        summary["timeseries_saved"] = upsert_timeseries(
            repository,
            source_code=args.source_code,
            indicator_rows=indicator_rows,
            data_rows=data_rows,
            summary=summary,
        )
    else:
        summary["timeseries_saved"] = 0

    output_path = (ROOT / args.summary_output).resolve()
    write_summary(output_path, summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2, default=str))


if __name__ == "__main__":
    main()
