create schema if not exists oil_research;

set search_path to oil_research;

create table if not exists dim_indicator (
    indicator_id bigint generated by default as identity primary key,
    indicator_code varchar(64) not null unique,
    indicator_name varchar(128) not null,
    category varchar(32) not null,
    sub_category varchar(32),
    unit varchar(32) not null,
    freq varchar(16) not null,
    value_type varchar(16) not null,
    publish_lag_rule varchar(128),
    fill_policy_default varchar(32) not null,
    description text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists dim_entity (
    entity_id bigint generated by default as identity primary key,
    entity_type varchar(32) not null,
    entity_code varchar(64) not null unique,
    entity_name varchar(128) not null,
    parent_entity_id bigint references dim_entity(entity_id),
    region_level varchar(16),
    product_family varchar(32),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists dim_source (
    source_id bigint generated by default as identity primary key,
    source_code varchar(64) not null unique,
    source_name varchar(128) not null,
    source_type varchar(32) not null,
    priority integer not null default 100,
    sla_level varchar(16),
    owner_team varchar(64),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists app_user (
    user_id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    display_name varchar(128) not null,
    title varchar(128),
    password_hash varchar(128) not null,
    password_salt varchar(64) not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    last_login_at timestamptz
);

create table if not exists app_permission (
    permission_id bigint generated by default as identity primary key,
    permission_code varchar(64) not null unique,
    permission_name varchar(128) not null,
    module_code varchar(64) not null,
    description text,
    created_at timestamptz not null default now()
);

create table if not exists app_role (
    role_id bigint generated by default as identity primary key,
    role_code varchar(64) not null unique,
    role_name varchar(128) not null,
    description text,
    is_system boolean not null default true,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists app_role_permission (
    role_id bigint not null references app_role(role_id) on delete cascade,
    permission_id bigint not null references app_permission(permission_id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (role_id, permission_id)
);

create table if not exists app_user_role (
    user_id bigint not null references app_user(user_id) on delete cascade,
    role_id bigint not null references app_role(role_id) on delete cascade,
    granted_by bigint references app_user(user_id),
    granted_at timestamptz not null default now(),
    primary key (user_id, role_id)
);

create table if not exists app_user_permission (
    user_id bigint not null references app_user(user_id) on delete cascade,
    permission_id bigint not null references app_permission(permission_id) on delete cascade,
    granted_by bigint references app_user(user_id),
    granted_at timestamptz not null default now(),
    primary key (user_id, permission_id)
);

create table if not exists app_user_session (
    session_id bigint generated by default as identity primary key,
    user_id bigint not null references app_user(user_id) on delete cascade,
    session_token_hash varchar(128) not null unique,
    expires_at timestamptz not null,
    ip_address varchar(64),
    user_agent varchar(256),
    created_at timestamptz not null default now(),
    revoked_at timestamptz,
    last_seen_at timestamptz not null default now()
);

create index if not exists idx_app_user_session_user on app_user_session (user_id, expires_at desc);

create table if not exists app_usage_log (
    usage_id bigint generated by default as identity primary key,
    user_id bigint references app_user(user_id) on delete set null,
    username varchar(64),
    action varchar(64) not null,
    method varchar(16),
    path varchar(256) not null,
    status_code integer,
    ip_address varchar(64),
    user_agent varchar(256),
    duration_ms integer,
    detail jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_app_usage_log_created_at on app_usage_log (created_at desc);
create index if not exists idx_app_usage_log_user on app_usage_log (user_id, created_at desc);
create index if not exists idx_app_usage_log_action on app_usage_log (action, created_at desc);

create table if not exists ods_raw_market (
    raw_id bigint generated by default as identity primary key,
    source_id bigint not null references dim_source(source_id),
    source_record_id varchar(128) not null,
    topic varchar(64) not null,
    source_event_time timestamptz,
    ingest_time timestamptz not null default now(),
    payload jsonb not null,
    payload_hash varchar(64) not null,
    dt date not null,
    unique (source_id, source_record_id, payload_hash)
);

create index if not exists idx_ods_raw_market_dt on ods_raw_market (dt);
create index if not exists idx_ods_raw_market_topic_time on ods_raw_market (topic, source_event_time desc);

create table if not exists ods_raw_forecast (
    raw_id bigint generated by default as identity primary key,
    source_id bigint not null references dim_source(source_id),
    report_date date not null,
    report_title varchar(256),
    source_record_id varchar(128) not null,
    fetched_at timestamptz not null default now(),
    payload jsonb not null,
    markdown_body text,
    payload_hash varchar(64) not null,
    dt date not null,
    unique (source_id, source_record_id, payload_hash)
);

create index if not exists idx_ods_raw_forecast_report_date on ods_raw_forecast (report_date desc);

create table if not exists ods_raw_news (
    raw_id bigint generated by default as identity primary key,
    source_id bigint not null references dim_source(source_id),
    source_record_id varchar(128) not null,
    publish_time timestamptz not null,
    title text,
    content text not null,
    author varchar(128),
    payload jsonb not null,
    payload_hash varchar(64) not null,
    ingest_time timestamptz not null default now(),
    dt date not null,
    unique (source_id, source_record_id, payload_hash)
);

create index if not exists idx_ods_raw_news_publish_time on ods_raw_news (publish_time desc);

create table if not exists ods_raw_calendar (
    raw_id bigint generated by default as identity primary key,
    calendar_type varchar(32) not null,
    calendar_date date not null,
    payload jsonb not null,
    source_id bigint not null references dim_source(source_id),
    ingest_time timestamptz not null default now(),
    dt date not null,
    unique (calendar_type, calendar_date, source_id)
);

create index if not exists idx_ods_raw_calendar_date on ods_raw_calendar (calendar_date desc);

create table if not exists fact_market_timeseries (
    ts_id bigint generated by default as identity primary key,
    indicator_id bigint not null references dim_indicator(indicator_id),
    entity_id bigint not null references dim_entity(entity_id),
    observation_time timestamptz not null,
    publish_time timestamptz not null,
    freq varchar(16) not null,
    value_num numeric(20, 6),
    value_text text,
    unit varchar(32) not null,
    currency varchar(16),
    source_id bigint not null references dim_source(source_id),
    source_record_id varchar(128) not null,
    is_final boolean not null default true,
    revision_no integer not null default 1,
    quality_flag varchar(16) not null default 'ok',
    effective_from timestamptz not null,
    effective_to timestamptz,
    ingest_time timestamptz not null default now(),
    dt date not null,
    constraint chk_fact_market_timeseries_quality_flag
        check (quality_flag in ('ok', 'missing', 'outlier', 'revised', 'fallback')),
    unique (indicator_id, entity_id, observation_time, revision_no, source_id)
);

create index if not exists idx_fact_market_entity_indicator_obs
    on fact_market_timeseries (entity_id, indicator_id, observation_time desc);
create index if not exists idx_fact_market_publish_time
    on fact_market_timeseries (publish_time desc);
create index if not exists idx_fact_market_dt
    on fact_market_timeseries (dt);
create index if not exists idx_fact_market_source_dt
    on fact_market_timeseries (source_id, dt desc);
create index if not exists idx_fact_market_source_indicator_dt
    on fact_market_timeseries (source_id, indicator_id, dt, publish_time desc);

create table if not exists fact_forecast_snapshot (
    forecast_id bigint generated by default as identity primary key,
    indicator_id bigint not null references dim_indicator(indicator_id),
    entity_id bigint not null references dim_entity(entity_id),
    forecast_target_time timestamptz not null,
    forecast_horizon varchar(16) not null,
    forecast_direction varchar(16),
    forecast_point numeric(20, 6),
    forecast_lower numeric(20, 6),
    forecast_upper numeric(20, 6),
    support_level numeric(20, 6),
    resistance_level numeric(20, 6),
    confidence_label varchar(16),
    issue_time timestamptz not null,
    source_id bigint not null references dim_source(source_id),
    source_record_id varchar(128) not null,
    model_name varchar(64),
    model_version varchar(32),
    raw_excerpt text,
    ingest_time timestamptz not null default now(),
    dt date not null,
    constraint chk_fact_forecast_direction
        check (forecast_direction is null or forecast_direction in ('up', 'down', 'flat')),
    constraint chk_fact_forecast_confidence
        check (confidence_label is null or confidence_label in ('low', 'medium', 'high')),
    unique (indicator_id, entity_id, forecast_target_time, forecast_horizon, issue_time, source_id)
);

create index if not exists idx_fact_forecast_issue_time on fact_forecast_snapshot (issue_time desc);
create index if not exists idx_fact_forecast_target_time on fact_forecast_snapshot (forecast_target_time desc);

create table if not exists fact_news_event (
    event_id bigint generated by default as identity primary key,
    cluster_id varchar(64) not null,
    event_type varchar(64) not null,
    event_state varchar(16) not null,
    event_time timestamptz not null,
    publish_time timestamptz not null,
    latest_update_time timestamptz not null,
    source_id bigint not null references dim_source(source_id),
    source_record_id varchar(128) not null,
    title text,
    content text not null,
    geo_scope varchar(64),
    commodity_scope varchar(64),
    core_entity_code varchar(64),
    direction_supply smallint,
    direction_demand smallint,
    direction_price smallint,
    direction_crack smallint,
    intensity_score numeric(8, 4),
    confidence_score numeric(8, 4),
    novelty_score numeric(8, 4),
    time_to_effect_hours integer,
    half_life_hours integer,
    source_quality varchar(16),
    supporting_evidence jsonb,
    raw_payload jsonb,
    ingest_time timestamptz not null default now(),
    dt date not null,
    constraint chk_fact_news_event_state
        check (event_state in ('rumored', 'confirmed', 'revised', 'canceled', 'disputed')),
    constraint chk_fact_news_event_direction_supply
        check (direction_supply is null or direction_supply in (-1, 0, 1)),
    constraint chk_fact_news_event_direction_demand
        check (direction_demand is null or direction_demand in (-1, 0, 1)),
    constraint chk_fact_news_event_direction_price
        check (direction_price is null or direction_price in (-1, 0, 1)),
    constraint chk_fact_news_event_direction_crack
        check (direction_crack is null or direction_crack in (-1, 0, 1))
);

create index if not exists idx_fact_news_cluster on fact_news_event (cluster_id, latest_update_time desc);
create index if not exists idx_fact_news_event_time on fact_news_event (event_time desc);
create index if not exists idx_fact_news_event_type on fact_news_event (event_type);

create table if not exists fact_calendar_event (
    calendar_id bigint generated by default as identity primary key,
    calendar_type varchar(32) not null,
    calendar_date date not null,
    name varchar(128) not null,
    region_scope varchar(64),
    is_active boolean not null default true,
    payload jsonb,
    source_id bigint not null references dim_source(source_id),
    created_at timestamptz not null default now(),
    unique (calendar_type, calendar_date, name)
);

create index if not exists idx_fact_calendar_date on fact_calendar_event (calendar_date desc);

create table if not exists feature_registry (
    feature_name varchar(128) not null,
    feature_version varchar(32) not null,
    entity_type varchar(32) not null,
    owner_team varchar(64) not null,
    definition_expr text not null,
    source_dependencies jsonb not null,
    fill_policy varchar(32) not null,
    validation_rule jsonb,
    description text,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (feature_name, feature_version)
);

create table if not exists feature_snapshot (
    snapshot_id bigint generated by default as identity primary key,
    entity_id bigint not null references dim_entity(entity_id),
    as_of_time timestamptz not null,
    feature_name varchar(128) not null,
    feature_version varchar(32) not null,
    feature_value_num numeric(20, 6),
    feature_value_text text,
    data_version varchar(64) not null,
    feature_def_hash varchar(64) not null,
    pipeline_run_id varchar(64) not null,
    quality_flag varchar(16) not null default 'ok',
    staleness_hours integer,
    created_at timestamptz not null default now(),
    constraint fk_feature_snapshot_registry
        foreign key (feature_name, feature_version)
        references feature_registry(feature_name, feature_version),
    constraint chk_feature_snapshot_quality_flag
        check (quality_flag in ('ok', 'stale', 'missing', 'fallback')),
    unique (entity_id, as_of_time, feature_name, feature_version)
);

create index if not exists idx_feature_snapshot_lookup
    on feature_snapshot (entity_id, as_of_time desc, feature_name, feature_version);
create index if not exists idx_feature_snapshot_pipeline
    on feature_snapshot (pipeline_run_id);

create table if not exists feature_materialization_log (
    pipeline_run_id varchar(64) primary key,
    job_name varchar(64) not null,
    as_of_time timestamptz not null,
    data_version varchar(64) not null,
    code_commit varchar(64),
    status varchar(16) not null,
    row_count integer,
    error_message text,
    started_at timestamptz not null,
    finished_at timestamptz,
    constraint chk_feature_materialization_status
        check (status in ('success', 'failed', 'partial'))
);

create table if not exists prediction_run (
    prediction_id bigint generated by default as identity primary key,
    run_id varchar(64) not null,
    entity_id bigint not null references dim_entity(entity_id),
    product_code varchar(32) not null,
    region_code varchar(32) not null,
    horizon varchar(16) not null,
    prediction_type varchar(16) not null,
    as_of_time timestamptz not null,
    target_start_time timestamptz,
    target_end_time timestamptz,
    direction_label varchar(16),
    prob_up numeric(8, 4),
    prob_flat numeric(8, 4),
    prob_down numeric(8, 4),
    point_value numeric(20, 6),
    range_lower numeric(20, 6),
    range_upper numeric(20, 6),
    crack_direction varchar(16),
    crack_point numeric(20, 6),
    confidence_label varchar(16) not null,
    confidence_score numeric(8, 4) not null,
    degrade_flag boolean not null default false,
    degrade_reason varchar(128),
    publish_status varchar(16) not null default 'draft',
    created_at timestamptz not null default now(),
    published_at timestamptz,
    constraint chk_prediction_run_direction
        check (direction_label is null or direction_label in ('up', 'down', 'flat')),
    constraint chk_prediction_run_type
        check (prediction_type in ('trend', 'point', 'range', 'crack')),
    constraint chk_prediction_run_confidence
        check (confidence_label in ('low', 'medium', 'high')),
    constraint chk_prediction_run_publish_status
        check (publish_status in ('draft', 'review_required', 'published', 'blocked'))
);

create index if not exists idx_prediction_run_lookup
    on prediction_run (product_code, region_code, horizon, as_of_time desc);
create index if not exists idx_prediction_run_publish_status
    on prediction_run (publish_status, created_at desc);

alter table prediction_run
    add column if not exists input_hash varchar(64),
    add column if not exists model_version varchar(64),
    add column if not exists runtime_control_snapshot jsonb,
    add column if not exists raw_context jsonb;

create unique index if not exists idx_prediction_run_input_hash
    on prediction_run (input_hash)
    where input_hash is not null;

create table if not exists prediction_factor_breakdown (
    id bigint generated by default as identity primary key,
    prediction_id bigint not null references prediction_run(prediction_id) on delete cascade,
    factor_group varchar(32) not null,
    factor_name varchar(128) not null,
    factor_value numeric(20, 6),
    factor_score numeric(20, 6),
    weight numeric(12, 6),
    contribution numeric(20, 6),
    evidence_ref jsonb
);

create index if not exists idx_prediction_factor_breakdown_prediction
    on prediction_factor_breakdown (prediction_id, factor_group);

create table if not exists agent_run_log (
    agent_run_id bigint generated by default as identity primary key,
    run_id varchar(64) not null,
    agent_name varchar(64) not null,
    agent_round integer not null default 1,
    input_context jsonb not null,
    claim_json jsonb,
    status varchar(16) not null,
    started_at timestamptz not null,
    finished_at timestamptz,
    error_message text,
    constraint chk_agent_run_log_status
        check (status in ('success', 'failed', 'skipped'))
);

create index if not exists idx_agent_run_log_run on agent_run_log (run_id, agent_name, agent_round);

create table if not exists manual_override_log (
    override_id bigint generated by default as identity primary key,
    prediction_id bigint not null references prediction_run(prediction_id),
    override_level varchar(8) not null,
    before_value jsonb not null,
    after_value jsonb not null,
    reason_code varchar(64) not null,
    reason_text text,
    requested_by varchar(64) not null,
    approved_by varchar(64),
    approved_at timestamptz,
    created_at timestamptz not null default now(),
    constraint chk_manual_override_level
        check (override_level in ('L1', 'L2', 'L3'))
);

create index if not exists idx_manual_override_prediction on manual_override_log (prediction_id, created_at desc);

create table if not exists publish_audit_log (
    audit_id bigint generated by default as identity primary key,
    prediction_id bigint not null references prediction_run(prediction_id),
    action_type varchar(32) not null,
    actor varchar(64) not null,
    target_channel varchar(32),
    action_time timestamptz not null default now(),
    extra_payload jsonb
);

create index if not exists idx_publish_audit_prediction on publish_audit_log (prediction_id, action_time desc);

create table if not exists alert_case (
    alert_id varchar(64) primary key,
    title text not null,
    category varchar(32) not null,
    event_type varchar(64),
    severity varchar(16) not null,
    alert_score numeric(12, 4),
    status varchar(16) not null default 'new',
    affected_region varchar(64),
    affected_product varchar(64),
    direction_price varchar(16),
    expected_impact varchar(64),
    confidence varchar(16),
    recommended_action text,
    source_name varchar(128),
    source_url text,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    confirmed_by varchar(64),
    confirmed_at timestamptz,
    resolved_by varchar(64),
    resolved_at timestamptz,
    review_note text,
    raw_payload jsonb,
    constraint chk_alert_case_status
        check (status in ('new', 'reviewing', 'tracking', 'resolved', 'dismissed')),
    constraint chk_alert_case_severity
        check (severity in ('高', '中', '低'))
);

create index if not exists idx_alert_case_status_score
    on alert_case (status, severity, alert_score desc, last_seen_at desc);

create table if not exists regional_freight_setting (
    region_code varchar(64) primary key,
    region_name varchar(128) not null,
    freight_value numeric(20, 6) not null,
    unit varchar(32) not null default '元/吨',
    source_type varchar(32) not null default 'manual',
    updated_by varchar(64),
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create index if not exists idx_regional_freight_updated
    on regional_freight_setting (updated_at desc);

create table if not exists business_action_recommendation (
    action_id bigint generated by default as identity primary key,
    run_id varchar(64) not null,
    action_type varchar(32) not null,
    title varchar(128) not null,
    action text not null,
    trigger_condition text,
    price_limit numeric(20, 6),
    volume_suggestion varchar(64),
    valid_until timestamptz,
    risk_stop text,
    owner_role varchar(64),
    priority varchar(16) not null default 'medium',
    rationale text,
    created_at timestamptz not null default now()
);

create index if not exists idx_business_action_run
    on business_action_recommendation (run_id, action_type);
